version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: task_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  persistence-service:
    build:
      context: .
      dockerfile: services/persistence-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/task_agent
      - RUST_LOG=info
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  case-management-service:
    build:
      context: .
      dockerfile: services/case-management-service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8001
      - RUST_LOG=info
    depends_on:
      - persistence-service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  task-management-service:
    build:
      context: .
      dockerfile: services/task-management-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8001
      - RUST_LOG=info
    depends_on:
      - persistence-service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ai-agent-service:
    build:
      context: .
      dockerfile: services/ai-agent-service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8001
      - CASE_MANAGEMENT_SERVICE_URL=http://case-management-service:8002
      - TASK_MANAGEMENT_SERVICE_URL=http://task-management-service:8003
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RUST_LOG=info
    depends_on:
      - persistence-service
      - case-management-service
      - task-management-service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  channel-service:
    build:
      context: .
      dockerfile: services/channel-service/Dockerfile
    ports:
      - "8005:8005"
    environment:
      - AI_AGENT_SERVICE_URL=http://ai-agent-service:8004
      - RUST_LOG=info
    depends_on:
      - ai-agent-service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  dashboard-service:
    build:
      context: .
      dockerfile: services/dashboard-service/Dockerfile
    ports:
      - "8006:8006"
    environment:
      - PERSISTENCE_SERVICE_URL=http://persistence-service:8001
      - CASE_MANAGEMENT_SERVICE_URL=http://case-management-service:8002
      - TASK_MANAGEMENT_SERVICE_URL=http://task-management-service:8003
      - CHANNEL_SERVICE_URL=http://channel-service:8005
      - RUST_LOG=info
    depends_on:
      - persistence-service
      - case-management-service
      - task-management-service
      - channel-service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  email-collector-service:
    build:
      context: .
      dockerfile: services/email-collector-service/Dockerfile
    ports:
      - "8007:8007"
    environment:
      - CHANNEL_SERVICE_URL=http://channel-service:8005
      - RUST_LOG=info
    depends_on:
      - channel-service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    env_file:
      - services/email-collector-service/.env

volumes:
  postgres_data:
